# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: "Dockerfile"
#     ports:
#       - "8080:8080"
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       - DB_HOST=db
#       - DB_USER=postgres
#       - DB_PASSWORD=qwe123
#       - DB_NAME=feedbox
#       - DB_PORT=5432
#       - DB_SSL_MODE=disable
#       - CONFIG_PATH=/app/local.yaml
#     volumes:
#        - ./local.yaml:/app/local.yaml:ro
#     restart: unless-stopped

#   db:
#     image: postgres:16
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=qwe123
#       - POSTGRES_DB=feedbox
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./docker/init:/docker-entrypoint-initdb.d
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d feedbox"]
#       interval: 5s
#       timeout: 5s
#       retries: 10
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data:



version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=qwe123
      - DB_NAME=feedbox
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - CONFIG_PATH=/app/local.yaml
    volumes:
      - ./local.yaml:/app/local.yaml:ro
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=feedbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d feedbox"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

volumes:
  postgres_data: